const produtos = [
  {
    nome: "Bird Couple",
    preco: 100,
    secao: "Paint in Acrylic",
    categoria: "acrylic",
    img: "./src/img/acrilico1.jpg",
  },
  {
    nome: "Gouse Couple",
    preco: 100,
    secao: "Paint in Acrylic",
    categoria: "acrylic",
    img: "./src/img/acrilico2.png",
  },
  {
    nome: "Kiwi Background",
    preco: 20,
    secao: "Paint in Watercolor",
    categoria: "watercolor",
    img: "./src/img/aquarela1.png",
  },
  {
    nome: "Daisy Background",
    preco: 20,
    secao: "Paint in Watercolor",
    categoria: "watercolor",
    img: "./src/img/aquarela2.png",
  },
  {
    nome: "Lime Background",
    preco: 20,
    secao: "Paint in Watercolor",
    categoria: "watercolor",
    img: "./src/img/aquarela3.png",
  },
  {
    nome: "Chick Cloud",
    preco: 50,
    secao: "Paint in Guache",
    categoria: "guache",
    img: "./src/img/guache1.png",
  },
  {
    nome: "Pink Van Gogh",
    preco: 80,
    secao: "Paint in Guache",
    categoria: "guache",
    img: "./src/img/guache2.png",
  },
  {
    nome: "Flowers at Night",
    preco: 30,
    secao: "Paint in Guache",
    categoria: "guache",
    img: "./src/img/guache3.png",
  },
];
