const produtos = [
  {
    id: 1,
    nome: "Bird Couple",
    preco: 100,
    secao: "Paint in Acrylic",
    categoria: "acrylic",
    img: "./src/img/acrilico1.jpg",
    promocao: false,
    precoPromocao: "0",
    componentes: ["Wood frame", "Acrylic paint", "Glossy varnish"],
  },

  {
    id: 2,
    nome: "Gouse Couple",
    preco: 100,
    secao: "Paint in Acrylic",
    categoria: "acrylic",
    img: "./src/img/acrilico2.png",
    promocao: true,
    precoPromocao: "50",
    componentes: ["Wood frame", "Acrylic paint", "Matte varnish"],
  },
  {
    id: 3,
    nome: "Kiwi Background",
    preco: 20,
    secao: "Paint in Watercolor",
    categoria: "watercolor",
    img: "./src/img/aquarela1.png",
    promocao: false,
    precoPromocao: "0",
    componentes: [
      "Watercolor papel 500g/m²",
      "Winsor and Newton paint",
      "Matte varnish",
    ],
  },
  {
    id: 4,
    nome: "Daisy Background",
    preco: 20,
    secao: "Paint in Watercolor",
    categoria: "watercolor",
    img: "./src/img/aquarela2.png",
    promocao: false,
    precoPromocao: "0",
    componentes: [
      "Watercolor papel 500g/m²",
      "Winsor and Newton paint",
      "Matte varnish",
    ],
  },
  {
    id: 5,
    nome: "Lime Background",
    preco: 20,
    secao: "Paint in Watercolor",
    categoria: "watercolor",
    img: "./src/img/aquarela3.png",
    promocao: false,
    precoPromocao: "0",
    componentes: [
      "Watercolor papel 500g/m²",
      "Winsor and Newton paint",
      "Matte varnish",
    ],
  },
  {
    id: 6,
    nome: "Chick Cloud",
    preco: 50,
    secao: "Paint in Guache",
    categoria: "guache",
    img: "./src/img/guache1.png",
    promocao: true,
    precoPromocao: "40",
    componentes: ["Wood frame", "Arttools paint", "Glossy varnish"],
  },
  {
    id: 7,
    nome: "Pink Van Gogh",
    preco: 80,
    secao: "Paint in Guache",
    categoria: "guache",
    img: "./src/img/guache2.png",
    promocao: false,
    precoPromocao: "0",
    componentes: ["Watercolor paper 300g/m²", "Arttools paint", "No varnish"],
  },
  {
    id: 8,
    nome: "Flowers at Night",
    preco: 30,
    secao: "Paint in Guache",
    categoria: "guache",
    img: "./src/img/guache3.png",
    promocao: false,
    precoPromocao: "0",
    componentes: ["Wood frame", "Arttools paint", "Glossy varnish"],
  },
];
